src/correction_engine_service/domain/value_objects/correction_mode.py: error: Source file found twice under different module names: "correction_engine_service.domain.value_objects.correction_mode" and "src.correction_engine_service.domain.value_objects.correction_mode"
src/correction_engine_service/domain/value_objects/correction_mode.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
src/correction_engine_service/domain/value_objects/correction_mode.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
